aliases:
  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages
  - &install
    pkg-manager: yarn
    override-ci-command: yarn install --immutable && yarn build:js
    cache-path: ~/.yarn/berry/cache
    include-branch-in-cache-key: false
    app-dir: ~/jest

orbs:
  node: circleci/node@4.0.0
version: 2.1
jobs:
  test-node-10:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '10'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-jest-jasmine:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          lts: true
          install-npm: false
      - node/install-packages: *install
      - run:
          command: JEST_JASMINE=1 yarn test-ci-partial && JEST_JASMINE=1 yarn test-leak
      - store_test_results:
          path: reports/junit

  test-node-12:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '12'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-node-14:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '14'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci
      - store_test_results:
          path: reports/junit

  test-node-15:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - run:
          command: |
            source ".circleci/parse-tag.sh"
            DOCKERHUB_DOCKEFILE="$DOCKERHUB_DOCKEFILE_ARM64"
            DOCKERHUB_DESTINATION="$DOCKERHUB_REPO:$LATEST_TAG-arm64v8"
            if [ -f $DOCKERHUB_DOCKEFILE ]; then
                #
                # Make sure the builder is copy the arm emulator
                sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
                sudo apt update
                sudo apt install -y qemu qemu-user-static qemu-user binfmt-support
                sudo cp /usr/bin/qemu-aarch64-static "$(dirname "$DOCKERHUB_DOCKEFILE")/qemu-aarch64-static"
                sed -i -e 's/#EnableQEMU //g' "$DOCKERHUB_DOCKEFILE"
                #
                source ".circleci/push-image.sh"
            else
                echo "Skipping linuxarm64v8 because $DOCKERHUB_DOCKEFILE is not found"
            fi
      - node/install:
          node-version: '15'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-node-10
      - test-node-12
      - test-node-14
      - test-node-15 # current
      - test-jest-jasmine
